name: dan-still-wordpress-site
recipe: wordpress
config:
  webroot: .
  php: '8.0'
  database: mysql

services:
  appserver: 
    type: php:8.0 # Specify the PHP version for the appserver
    build:
      - "composer install --no-dev --no-interaction --prefer-dist" # Example: run composer install on build
    environment:
      WP_ENV: development # <-- Add this line for development environment detection

  mysql:
    type: mysql:5.7
    portforward: true

tooling:
  composer:
    service: appserver
    cmd: composer

  yarn:
    service: appserver
    cmd: yarn

  sass:
    service: appserver
    cmd: sass

  npm:
    service: appserver
    cmd: npm

  build:
    service: appserver
    cmd: yarn build

  dev:
    service: appserver
    cmd: yarn dev

proxy:
  appserver:
    - dan-still-wordpress-site.lndo.site