<?php

/*
|--------------------------------------------------------------------------
| Register The Auto Loader
|--------------------------------------------------------------------------
|
| Composer provides a convenient, automatically generated class loader for
| our theme. We will simply require it into the script here so that we
| don't have to worry about manually loading any of our classes later on.
|
*/

if (! file_exists($composer = __DIR__.'/vendor/autoload.php')) {
    wp_die(__('Error locating autoloader. Please run <code>composer install</code>.', 'sage'));
}

require $composer;

/*
|--------------------------------------------------------------------------
| Register The Bootloader
|--------------------------------------------------------------------------
|
| The first thing we will do is schedule a new Acorn application container
| to boot when WordPress is finished loading the theme. The application
| serves as the "glue" for all the components of Laravel and is
| the IoC container for the system binding all of the various parts.
|
*/

try {
    \Roots\bootloader();
} catch (Throwable $e) {
    wp_die(
        __('You need to install Acorn to use this theme.', 'sage'),
        '',
        [
            'link_url' => 'https://docs.roots.io/acorn/2.x/installation/',
            'link_text' => __('Acorn Docs: Installation', 'sage'),
        ]
    );
}

/*
|--------------------------------------------------------------------------
| Register Sage Theme Files
|--------------------------------------------------------------------------
|
| Out of the box, Sage ships with categorically named theme files
| containing common functionality and setup to be bootstrapped with your
| theme. Simply add (or remove) files from the array below to change what
| is registered alongside Sage.
|
*/

collect(['setup', 'filters'])
    ->each(function ($file) {
        if (! locate_template($file = "app/{$file}.php", true, true)) {
            wp_die(
                /* translators: %s is replaced with the relative file path */
                sprintf(__('Error locating <code>%s</code> for inclusion.', 'sage'), $file)
            );
        }
    });

    <?php
    /**
     * Theme functions.php
     */
    
    // Enqueue Bud assets
    function danpress_enqueue_assets() {
        // Get the theme directory URI
        $theme_uri = get_template_directory_uri();
        // Get the path to your compiled assets directory (e.g., 'public' within your theme)
        $dist_uri = $theme_uri . '/public';
    
        // Check if the manifest.json exists (Bud generates this)
        // In development (when `yarn dev` is running), Bud often serves assets directly
        // and `manifest.json` might not be immediately available, or URLs might be different.
        // It's best to handle dev vs. production URLs.
    
        // DEVELOPMENT MODE: When `yarn dev` is running, Bud serves assets from its own server.
        // We'll use a placeholder URL that Bud intercepts.
        if ( defined( 'WP_ENV' ) && WP_ENV === 'development' ) {
            // This is a common pattern for Bud/Webpack dev servers
            $bud_dev_url = 'http://localhost:3000'; // Make sure this matches your .setUrl() in bud.config.js
            $dist_uri = $bud_dev_url . '/public'; // Bud's dev server serves from its public path
    
            // Add your main app.css
            wp_enqueue_style(
                'danpress-app-css',
                $dist_uri . '/css/app.css', // This path is relative to Bud's dev server public folder
                [],
                null // Use null for version in development to ensure latest
            );
    
            // Add your main app.js
            wp_enqueue_script(
                'danpress-app-js',
                $dist_uri . '/js/app.js', // This path is relative to Bud's dev server public folder
                ['jquery'], // Or other dependencies if needed, e.g., []
                null, // Use null for version in development
                true // Load in footer
            );
    
        } else {
            // PRODUCTION MODE: After `yarn build`, assets are in your theme's `public` directory.
            // We'll use the manifest.json generated by Bud for hashed filenames.
            $manifest_path = get_template_directory() . '/public/entrypoints.json'; // Bud 6+ uses entrypoints.json
            if ( file_exists( $manifest_path ) ) {
                $manifest = json_decode( file_get_contents( $manifest_path ), true );
    
                // Enqueue CSS
                if ( isset( $manifest['app']['css'] ) ) {
                    foreach ( $manifest['app']['css'] as $css_file ) {
                        wp_enqueue_style(
                            'danpress-' . sanitize_title( basename( $css_file, '.css' ) ),
                            $dist_uri . '/' . $css_file,
                            [],
                            null // Or hash from manifest for version
                        );
                    }
                }
    
                // Enqueue JS
                if ( isset( $manifest['app']['js'] ) ) {
                    foreach ( $manifest['app']['js'] as $js_file ) {
                        wp_enqueue_script(
                            'danpress-' . sanitize_title( basename( $js_file, '.js' ) ),
                            $dist_uri . '/' . $js_file,
                            ['jquery'], // Or other dependencies
                            null, // Or hash from manifest for version
                            true // Load in footer
                        );
                    }
                }
            }
        }
    }
    add_action( 'wp_enqueue_scripts', 'danpress_enqueue_assets' );
    
    // Optional: Define WP_ENV for easier dev/production switching
    // You can set this in your wp-config.php or Lando configuration
    // For Lando, you'd add something like this in your .lando.yml under environment:
    //   WP_ENV: development
    // Or in wp-config.php:
    // define('WP_ENV', 'development'); // for local
    // define('WP_ENV', 'production'); // for live
    if ( ! defined( 'WP_ENV' ) ) {
        define( 'WP_ENV', 'production' ); // Default to production if not set
    }

add_theme_support('sage');
